#Application Configuration

#application:
#  title: @project.name@
#  version: @project.version@
#  author: Raúl Ponce

server:
  port: 8081
spring:
  application:
    name: api-rest-customers
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customers-db
      
info:
  app:
    app-name: Customers Microservices
    description: Microservicio para el manejo de clientes
    version: 1.0
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator  
    