#Application Configuration

application:
  title: @project.name@
  version: @project.version@
  author: Raúl Ponce

server:
  port: 8084
spring:
  application:
    name: api-rest-transactions
  data:
    mongodb:
      host: localhost
      port: 27017
      database: transaction-db

config:
  base:
    endpoint:
      customers: http://localhost:8081/api/customers
      accounts: http://localhost:8082/api/accounts
      credits: http://localhost:8083/api/credits

limit:
  credits-customer-personal: 1
  transactions: 20

commission: 5.00