#Application Configuration

#application:
#  title: @project.name@
#  version: @project.version@
#  author: Raúl Ponce

server:
  port: 8086
spring:
  application:
    name: api-rest-debit-cards
  data:
    mongodb:
      host: localhost
      port: 27017
      database: debit-cards-db

config:
  base:
    endpoint:
      customers: http://localhost:8081/api/customers
      accounts: http://localhost:8082/api/accounts
      credits: http://localhost:8083/api/credits

limit:
  saving-accounts: 1
  current-accounts: 1
  authorized-signers: 4