server:
  port: 8081
spring:
  application:
    name: api-rest-customers
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customers-db
      
info:
  app:
    app-name: Customers Microservices
    description: Microservicio para el manejo de clientes
    version: 1.0
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator  
   
### CircuitBreaker Configuration
resilience4j:
  circuitbreaker:
    configs:
      customProductService:
        slidingWindowSize: 20
        failureRateThreshold: 70
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 70
    instances:
      product-service:
        base-config: customProductService