server:
  port: 8088
spring:
  application:
    name: api-rest-wallet-movil-yanki
  data:
    mongodb:
      host: localhost
      port: 27017
      database: walletmovil-db

config:
  base:
    endpoint:
      customers: http://localhost:8081/api/customers
      accounts: http://localhost:8082/api/accounts
      credits: http://localhost:8083/api/credits
      transactions: http://localhost:8084/api/transactions
      credit-cards: http://localhost:8085/api/creditcards
      debit-cards: http://localhost:8086/api/debit-cards