#Application Configuration

application:
  title: @project.name@
  version: @project.version@
  author: Raúl Ponce

server:
  port: 8083
spring:
  application:
    name: api-rest-credits
  data:
    mongodb:
      host: localhost
      port: 27017
      database: credit-db

config:
  base:
    endpoint:
      customers: http://localhost:8081/api/customers

limit:
  credits-customer-personal: 1