#Application Configuration

#application:
#  title: @project.name@
#  version: @project.version@
#  author: Raúl Ponce

server:
  port: 8082
spring:
  application:
    name: api-rest-accounts
  data:
    mongodb:
      host: localhost
      port: 27017
      database: account-db

config:
  base:
    endpoint:
      customers: http://localhost:8081/api/customers
      transactions: http://localhost:8084/api/transactions
      creditcards: http://localhost:8085/api/creditcards

limit:
  saving-accounts: 1
  current-accounts: 1
  authorized-signers: 4