#Application Configuration

#application:
#  title: @project.name@
#  version: @project.version@
#  author: Raúl Ponce

server:
  port: 8085
spring:
  application:
    name: api-rest-credit-cards
  data:
    mongodb:
      host: localhost
      port: 27017
      database: credit-cards-db

config:
  base:
    endpoint:
      customers: http://localhost:8081/api/customers

limit:
  credits-customer-personal: 1